### PR TITLE
Finalize go player

### PR DESCRIPTION
**Pull request by devill**
Please merge this pull request, and then transfer ownership of the repo to the lean-poker organization

### CODE REVIEW

**Comment by devill** [comment]
Can you please transfer ownership to the lean-poker organization? Let me know when you are doing it, so that I can delete the fork there. (Otherwise you might not be able to do the ownership transfer.)

**Comment by devill** [comment]
Actually I went ahead, and deleted the repo, now you should be able to transfer ownership

**Comment by ziegfried** [comment]
It should already be transferred. Cheers!

**Comment by devill** [comment]
It didn't show up yet. :(

**Comment by ziegfried** [comment]
I tried again but it says I don't have admin rights anymore.

**Comment by devill** [comment]
Ok! I know what's wrong! I invited you with the necessary rights!

**Comment by ziegfried** [comment]
Cool! It's all done now.

**Comment by devill** [comment]
Yes! Thanks!

**Pull request merged**
