### PR TITLE
Minor improvements and code formatting

### PR DESCRIPTION
**Pull request by andrewslotin**
* Updated import paths to use github.com/lean-poker/poker-player-go
* Extract `Game`, `Player` and `Card` to `github.com/lean-poker/poker-player-go/leanpoker`
* Added quotes to JSON annotations field names
* Cleaned up code and formatted using `gofmt`

### CODE REVIEW

**Comment by devill** [comment]
Thank you for the pull request!

**Comment by andrewslotin** [comment]
Yay! :+1:

**Comment by devill** [comment]
If you have a bit more time there are two issues with this framework: 
- All player frameworks should use a dynamic structure as the game state, since the game state is subject to change. I can't keep modifying 15 repos every time the game state is changed. Something like a map should be used.
- Please see if it's possible to make sure that when the repo is forked nothing needs to be updated. (See the usage instructions in the README.md... that should be unnecessary.)

It would be really awesome, if you could take care of those :)

**Comment by andrewslotin** [comment]
I'll try to have a look.

**Comment by devill** [comment]
Thanks! :)

**Pull request merged**
