### PR TITLE
Updated to newer go 1.7 version

### PR DESCRIPTION
**Pull request by syzer**

### CODE REVIEW

**Comment by syzer** [comment]
It works. We tested with heroku and locally.

```
git push heroku master
Counting objects: 130, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (69/69), done.
Writing objects: 100% (130/130), 16.84 KiB | 0 bytes/s, done.
Total 130 (delta 51), reused 125 (delta 50)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Go app detected
remote: -----> Checking Godeps/Godeps.json file.
remote: -----> Installing go1.7.1... done
remote: -----> Running: go install -v -tags heroku ./...
remote: github.com/lean-poker/poker-player-go/leanpoker
remote: github.com/lean-poker/poker-player-go/player
remote: github.com/lean-poker/poker-player-go
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 1.9M
remote: -----> Launching...
remote:        Released v3
remote:        https://murmuring-island-99377.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/murmuring-island-99377.git
 * [new branch]      master -> master
```

**Comment by syzer** [comment]
`curl -d 'action=check' 'https://murmuring-island-99377.herokuapp.com:4711' -vvv`
`curl -d 'action=bet_request&game_state={
                                    "players":[
                                      {
                                        "name":"Player 1",
                                        "stack":1000,
                                        "status":"active",
                                        "bet":0,
                                        "hole_cards":[{"rank": "K", "suit": "clubs"}, {"rank": "J", "suit": "clubs"}],
                                        "version":"Version name 1",
                                        "id":0
                                      },
                                      {
                                        "name":"Player 2",
                                        "stack":1000,
                                        "status":"active",
                                        "bet":0,
                                        "hole_cards":[],
                                        "version":"Version name 2",
                                        "id":1
                                      }
                                    ],
                                    "tournament_id":"550d1d68cd7bd10003000003",
                                    "game_id":"550da1cb2d909006e90004b1",
                                    "round":0,
                                    "bet_index":0,
                                    "small_blind":10,
                                    "orbits":0,
                                    "dealer":0,
                                    "community_cards":[],
                                    "current_buy_in":0,
                                    "pot":0,
                                    "in_action": 0,
                                    "minimum_raise": 5
                                  }' 'https://murmuring-island-99377.herokuapp.com'`

**Comment by devill** [comment]
Thanks for the pull request. Merged it, and tested it :)

**Comment by syzer** [comment]
Awesome idea.. love those bots!

**Pull request merged**
